# Generated by Django 2.2.4 on 2019-09-12 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='decription',
            new_name='description',
        ),
    ]
