# Generated by Django 2.2.4 on 2019-09-13 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20190913_0519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='Product',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='user',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderProduct',
        ),
    ]
