# Generated by Django 2.2.4 on 2019-09-13 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_order_orderproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Ordered',
            new_name='ordered',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Ordered_date',
            new_name='ordered_date',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Product',
            new_name='products',
        ),
        migrations.RenameField(
            model_name='orderproduct',
            old_name='Ordered',
            new_name='ordered',
        ),
        migrations.RenameField(
            model_name='orderproduct',
            old_name='Product',
            new_name='product',
        ),
    ]
